# Generated by Django 2.0.6 on 2018-07-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(null=True),
        ),
    ]
