# Generated by Django 2.0.6 on 2018-07-19 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_postman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postman',
            name='user',
        ),
    ]
